# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snowflake',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('model_class', models.CharField(max_length=255)),
            ],
        ),
    ]
